# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: atelier_engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'atelier_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61telier_engine.proto\x12\x0e\x61telier.engine\"\x8a\x01\n\x0f\x43ompleteRequest\x12\x12\n\ncapability\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x15\n\rsystem_prompt\x18\x03 \x01(\t\x12\x12\n\nmax_tokens\x18\x04 \x01(\x05\x12\x13\n\x0btemperature\x18\x05 \x01(\x02\x12\x13\n\x0bjson_schema\x18\x06 \x01(\t\"\xa7\x01\n\x10\x43ompleteResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x15\n\rprompt_tokens\x18\x03 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x04 \x01(\x05\x12\x12\n\nlatency_ms\x18\x05 \x01(\x02\x12\x19\n\x11reasoning_content\x18\x06 \x01(\t\x12\x15\n\rfinish_reason\x18\x07 \x01(\t\"+\n\x15\x45nsureEndpointRequest\x12\x12\n\ncapability\x18\x01 \x01(\t\"s\n\x0e\x45ndpointStatus\x12\x12\n\ncapability\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0f\n\x07healthy\x18\x03 \x01(\x08\x12\x0c\n\x04port\x18\x04 \x01(\x05\x12\x0f\n\x07gpu_ids\x18\x05 \x03(\x05\x12\x0e\n\x06\x64\x65tail\x18\x06 \x01(\t\"\x15\n\x13\x45ngineStatusRequest\"]\n\x14\x45ngineStatusResponse\x12\x31\n\tendpoints\x18\x01 \x03(\x0b\x32\x1e.atelier.engine.EndpointStatus\x12\x12\n\ntotal_gpus\x18\x02 \x01(\x05\x32\x92\x02\n\rAtelierEngine\x12M\n\x08\x43omplete\x12\x1f.atelier.engine.CompleteRequest\x1a .atelier.engine.CompleteResponse\x12W\n\x0e\x45nsureEndpoint\x12%.atelier.engine.EnsureEndpointRequest\x1a\x1e.atelier.engine.EndpointStatus\x12Y\n\x0c\x45ngineStatus\x12#.atelier.engine.EngineStatusRequest\x1a$.atelier.engine.EngineStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'atelier_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPLETEREQUEST']._serialized_start=41
  _globals['_COMPLETEREQUEST']._serialized_end=179
  _globals['_COMPLETERESPONSE']._serialized_start=182
  _globals['_COMPLETERESPONSE']._serialized_end=349
  _globals['_ENSUREENDPOINTREQUEST']._serialized_start=351
  _globals['_ENSUREENDPOINTREQUEST']._serialized_end=394
  _globals['_ENDPOINTSTATUS']._serialized_start=396
  _globals['_ENDPOINTSTATUS']._serialized_end=511
  _globals['_ENGINESTATUSREQUEST']._serialized_start=513
  _globals['_ENGINESTATUSREQUEST']._serialized_end=534
  _globals['_ENGINESTATUSRESPONSE']._serialized_start=536
  _globals['_ENGINESTATUSRESPONSE']._serialized_end=629
  _globals['_ATELIERENGINE']._serialized_start=632
  _globals['_ATELIERENGINE']._serialized_end=906
# @@protoc_insertion_point(module_scope)
