# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from atelier.engine.proto import atelier_engine_pb2 as atelier__engine__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in atelier_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AtelierEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Complete = channel.unary_unary(
                '/atelier.engine.AtelierEngine/Complete',
                request_serializer=atelier__engine__pb2.CompleteRequest.SerializeToString,
                response_deserializer=atelier__engine__pb2.CompleteResponse.FromString,
                _registered_method=True)
        self.EnsureEndpoint = channel.unary_unary(
                '/atelier.engine.AtelierEngine/EnsureEndpoint',
                request_serializer=atelier__engine__pb2.EnsureEndpointRequest.SerializeToString,
                response_deserializer=atelier__engine__pb2.EndpointStatus.FromString,
                _registered_method=True)
        self.EngineStatus = channel.unary_unary(
                '/atelier.engine.AtelierEngine/EngineStatus',
                request_serializer=atelier__engine__pb2.EngineStatusRequest.SerializeToString,
                response_deserializer=atelier__engine__pb2.EngineStatusResponse.FromString,
                _registered_method=True)


class AtelierEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Complete(self, request, context):
        """Workload-facing: request an inference CAPABILITY. The engine selects + ensures
        the model and calls vLLM internally; the workload never sees a vLLM endpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnsureEndpoint(self, request, context):
        """Admin/observability for the engine-internal vLLM lifecycle (NOT how workloads
        do inference).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EngineStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AtelierEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=atelier__engine__pb2.CompleteRequest.FromString,
                    response_serializer=atelier__engine__pb2.CompleteResponse.SerializeToString,
            ),
            'EnsureEndpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsureEndpoint,
                    request_deserializer=atelier__engine__pb2.EnsureEndpointRequest.FromString,
                    response_serializer=atelier__engine__pb2.EndpointStatus.SerializeToString,
            ),
            'EngineStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.EngineStatus,
                    request_deserializer=atelier__engine__pb2.EngineStatusRequest.FromString,
                    response_serializer=atelier__engine__pb2.EngineStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'atelier.engine.AtelierEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('atelier.engine.AtelierEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AtelierEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atelier.engine.AtelierEngine/Complete',
            atelier__engine__pb2.CompleteRequest.SerializeToString,
            atelier__engine__pb2.CompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnsureEndpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atelier.engine.AtelierEngine/EnsureEndpoint',
            atelier__engine__pb2.EnsureEndpointRequest.SerializeToString,
            atelier__engine__pb2.EndpointStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EngineStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atelier.engine.AtelierEngine/EngineStatus',
            atelier__engine__pb2.EngineStatusRequest.SerializeToString,
            atelier__engine__pb2.EngineStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
