# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from atelier.proto import atelier_pb2 as atelier_dot_proto_dot_atelier__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/atelier/proto/atelier_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AtelierStub(object):
    """── Service ───────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/atelier.Atelier/HealthCheck',
                request_serializer=atelier_dot_proto_dot_atelier__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=atelier_dot_proto_dot_atelier__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/atelier.Atelier/ListAgents',
                request_serializer=atelier_dot_proto_dot_atelier__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=atelier_dot_proto_dot_atelier__pb2.ListAgentsResponse.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/atelier.Atelier/GetAgent',
                request_serializer=atelier_dot_proto_dot_atelier__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=atelier_dot_proto_dot_atelier__pb2.GetAgentResponse.FromString,
                _registered_method=True)
        self.ListDataSources = channel.unary_unary(
                '/atelier.Atelier/ListDataSources',
                request_serializer=atelier_dot_proto_dot_atelier__pb2.ListDataSourcesRequest.SerializeToString,
                response_deserializer=atelier_dot_proto_dot_atelier__pb2.ListDataSourcesResponse.FromString,
                _registered_method=True)
        self.ListDatasets = channel.unary_unary(
                '/atelier.Atelier/ListDatasets',
                request_serializer=atelier_dot_proto_dot_atelier__pb2.ListDatasetsRequest.SerializeToString,
                response_deserializer=atelier_dot_proto_dot_atelier__pb2.ListDatasetsResponse.FromString,
                _registered_method=True)
        self.GetFSMStatus = channel.unary_unary(
                '/atelier.Atelier/GetFSMStatus',
                request_serializer=atelier_dot_proto_dot_atelier__pb2.FSMStatusRequest.SerializeToString,
                response_deserializer=atelier_dot_proto_dot_atelier__pb2.FSMStatusResponse.FromString,
                _registered_method=True)
        self.StartClassification = channel.unary_unary(
                '/atelier.Atelier/StartClassification',
                request_serializer=atelier_dot_proto_dot_atelier__pb2.StartClassificationRequest.SerializeToString,
                response_deserializer=atelier_dot_proto_dot_atelier__pb2.StartClassificationResponse.FromString,
                _registered_method=True)


class AtelierServicer(object):
    """── Service ───────────────────────────────────────────────────────

    """

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataSources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatasets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFSMStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartClassification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AtelierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=atelier_dot_proto_dot_atelier__pb2.HealthCheckRequest.FromString,
                    response_serializer=atelier_dot_proto_dot_atelier__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=atelier_dot_proto_dot_atelier__pb2.ListAgentsRequest.FromString,
                    response_serializer=atelier_dot_proto_dot_atelier__pb2.ListAgentsResponse.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=atelier_dot_proto_dot_atelier__pb2.GetAgentRequest.FromString,
                    response_serializer=atelier_dot_proto_dot_atelier__pb2.GetAgentResponse.SerializeToString,
            ),
            'ListDataSources': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataSources,
                    request_deserializer=atelier_dot_proto_dot_atelier__pb2.ListDataSourcesRequest.FromString,
                    response_serializer=atelier_dot_proto_dot_atelier__pb2.ListDataSourcesResponse.SerializeToString,
            ),
            'ListDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatasets,
                    request_deserializer=atelier_dot_proto_dot_atelier__pb2.ListDatasetsRequest.FromString,
                    response_serializer=atelier_dot_proto_dot_atelier__pb2.ListDatasetsResponse.SerializeToString,
            ),
            'GetFSMStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFSMStatus,
                    request_deserializer=atelier_dot_proto_dot_atelier__pb2.FSMStatusRequest.FromString,
                    response_serializer=atelier_dot_proto_dot_atelier__pb2.FSMStatusResponse.SerializeToString,
            ),
            'StartClassification': grpc.unary_unary_rpc_method_handler(
                    servicer.StartClassification,
                    request_deserializer=atelier_dot_proto_dot_atelier__pb2.StartClassificationRequest.FromString,
                    response_serializer=atelier_dot_proto_dot_atelier__pb2.StartClassificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'atelier.Atelier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('atelier.Atelier', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Atelier(object):
    """── Service ───────────────────────────────────────────────────────

    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atelier.Atelier/HealthCheck',
            atelier_dot_proto_dot_atelier__pb2.HealthCheckRequest.SerializeToString,
            atelier_dot_proto_dot_atelier__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atelier.Atelier/ListAgents',
            atelier_dot_proto_dot_atelier__pb2.ListAgentsRequest.SerializeToString,
            atelier_dot_proto_dot_atelier__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atelier.Atelier/GetAgent',
            atelier_dot_proto_dot_atelier__pb2.GetAgentRequest.SerializeToString,
            atelier_dot_proto_dot_atelier__pb2.GetAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataSources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atelier.Atelier/ListDataSources',
            atelier_dot_proto_dot_atelier__pb2.ListDataSourcesRequest.SerializeToString,
            atelier_dot_proto_dot_atelier__pb2.ListDataSourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atelier.Atelier/ListDatasets',
            atelier_dot_proto_dot_atelier__pb2.ListDatasetsRequest.SerializeToString,
            atelier_dot_proto_dot_atelier__pb2.ListDatasetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFSMStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atelier.Atelier/GetFSMStatus',
            atelier_dot_proto_dot_atelier__pb2.FSMStatusRequest.SerializeToString,
            atelier_dot_proto_dot_atelier__pb2.FSMStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartClassification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atelier.Atelier/StartClassification',
            atelier_dot_proto_dot_atelier__pb2.StartClassificationRequest.SerializeToString,
            atelier_dot_proto_dot_atelier__pb2.StartClassificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
