# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/atelier/proto/atelier.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/atelier/proto/atelier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fsrc/atelier/proto/atelier.proto\x12\x07\x61telier\"\x14\n\x12HealthCheckRequest\"6\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"^\n\rAgentMetadata\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x10\n\x08tool_ids\x18\x05 \x03(\t\"\x13\n\x11ListAgentsRequest\"<\n\x12ListAgentsResponse\x12&\n\x06\x61gents\x18\x01 \x03(\x0b\x32\x16.atelier.AgentMetadata\"\x1d\n\x0fGetAgentRequest\x12\n\n\x02id\x18\x01 \x01(\t\"9\n\x10GetAgentResponse\x12%\n\x05\x61gent\x18\x01 \x01(\x0b\x32\x16.atelier.AgentMetadata\"o\n\x15\x43lassificationDataset\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0cparquet_path\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x11\n\trow_count\x18\x05 \x01(\x03\"\x15\n\x13ListDatasetsRequest\"H\n\x14ListDatasetsResponse\x12\x30\n\x08\x64\x61tasets\x18\x01 \x03(\x0b\x32\x1e.atelier.ClassificationDataset2\xb0\x02\n\x07\x41telier\x12J\n\x0bHealthCheck\x12\x1b.atelier.HealthCheckRequest\x1a\x1c.atelier.HealthCheckResponse\"\x00\x12G\n\nListAgents\x12\x1a.atelier.ListAgentsRequest\x1a\x1b.atelier.ListAgentsResponse\"\x00\x12\x41\n\x08GetAgent\x12\x18.atelier.GetAgentRequest\x1a\x19.atelier.GetAgentResponse\"\x00\x12M\n\x0cListDatasets\x12\x1c.atelier.ListDatasetsRequest\x1a\x1d.atelier.ListDatasetsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.atelier.proto.atelier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=44
  _globals['_HEALTHCHECKREQUEST']._serialized_end=64
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=66
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=120
  _globals['_AGENTMETADATA']._serialized_start=122
  _globals['_AGENTMETADATA']._serialized_end=216
  _globals['_LISTAGENTSREQUEST']._serialized_start=218
  _globals['_LISTAGENTSREQUEST']._serialized_end=237
  _globals['_LISTAGENTSRESPONSE']._serialized_start=239
  _globals['_LISTAGENTSRESPONSE']._serialized_end=299
  _globals['_GETAGENTREQUEST']._serialized_start=301
  _globals['_GETAGENTREQUEST']._serialized_end=330
  _globals['_GETAGENTRESPONSE']._serialized_start=332
  _globals['_GETAGENTRESPONSE']._serialized_end=389
  _globals['_CLASSIFICATIONDATASET']._serialized_start=391
  _globals['_CLASSIFICATIONDATASET']._serialized_end=502
  _globals['_LISTDATASETSREQUEST']._serialized_start=504
  _globals['_LISTDATASETSREQUEST']._serialized_end=525
  _globals['_LISTDATASETSRESPONSE']._serialized_start=527
  _globals['_LISTDATASETSRESPONSE']._serialized_end=599
  _globals['_ATELIER']._serialized_start=602
  _globals['_ATELIER']._serialized_end=906
# @@protoc_insertion_point(module_scope)
