[book]
authors = ["Ryan Hill"]
language = "en"
src = "src"
title = "Atelier"

[preprocessor.d2]
[preprocessor.mermaid]
# katex preprocessor disabled (0.9.4 incompatible with mdbook 0.5.2)

[output.html]
