# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from zndx.engine.v1 import engine_pb2 as zndx_dot_engine_dot_v1_dot_engine__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in zndx/engine/v1/engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Complete = channel.unary_unary(
                '/zndx.engine.v1.Engine/Complete',
                request_serializer=zndx_dot_engine_dot_v1_dot_engine__pb2.CompleteRequest.SerializeToString,
                response_deserializer=zndx_dot_engine_dot_v1_dot_engine__pb2.CompleteResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/zndx.engine.v1.Engine/Status',
                request_serializer=zndx_dot_engine_dot_v1_dot_engine__pb2.StatusRequest.SerializeToString,
                response_deserializer=zndx_dot_engine_dot_v1_dot_engine__pb2.StatusResponse.FromString,
                _registered_method=True)


class EngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Complete(self, request, context):
        """Request an inference CAPABILITY. The engine selects/ensures the model and serves internally;
        the caller never sees a model endpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """The federation-facing status surface: what capabilities this engine serves, on which GPUs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=zndx_dot_engine_dot_v1_dot_engine__pb2.CompleteRequest.FromString,
                    response_serializer=zndx_dot_engine_dot_v1_dot_engine__pb2.CompleteResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=zndx_dot_engine_dot_v1_dot_engine__pb2.StatusRequest.FromString,
                    response_serializer=zndx_dot_engine_dot_v1_dot_engine__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zndx.engine.v1.Engine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zndx.engine.v1.Engine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Engine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zndx.engine.v1.Engine/Complete',
            zndx_dot_engine_dot_v1_dot_engine__pb2.CompleteRequest.SerializeToString,
            zndx_dot_engine_dot_v1_dot_engine__pb2.CompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zndx.engine.v1.Engine/Status',
            zndx_dot_engine_dot_v1_dot_engine__pb2.StatusRequest.SerializeToString,
            zndx_dot_engine_dot_v1_dot_engine__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
