# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zndx/engine/v1/engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'zndx/engine/v1/engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bzndx/engine/v1/engine.proto\x12\x0ezndx.engine.v1\"\x8a\x01\n\x0f\x43ompleteRequest\x12\x12\n\ncapability\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x15\n\rsystem_prompt\x18\x03 \x01(\t\x12\x12\n\nmax_tokens\x18\x04 \x01(\x05\x12\x13\n\x0btemperature\x18\x05 \x01(\x02\x12\x13\n\x0bjson_schema\x18\x06 \x01(\t\"\xa7\x01\n\x10\x43ompleteResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x15\n\rprompt_tokens\x18\x03 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x04 \x01(\x05\x12\x12\n\nlatency_ms\x18\x05 \x01(\x02\x12\x19\n\x11reasoning_content\x18\x06 \x01(\t\x12\x15\n\rfinish_reason\x18\x07 \x01(\t\"\x0f\n\rStatusRequest\"_\n\x08\x45ndpoint\x12\x12\n\ncapability\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0f\n\x07healthy\x18\x03 \x01(\x08\x12\x0f\n\x07gpu_ids\x18\x04 \x03(\x05\x12\x0e\n\x06\x64\x65tail\x18\x05 \x01(\t\"b\n\x0eStatusResponse\x12\x0f\n\x07project\x18\x01 \x01(\t\x12+\n\tendpoints\x18\x02 \x03(\x0b\x32\x18.zndx.engine.v1.Endpoint\x12\x12\n\ntotal_gpus\x18\x03 \x01(\x05\x32\xa0\x01\n\x06\x45ngine\x12M\n\x08\x43omplete\x12\x1f.zndx.engine.v1.CompleteRequest\x1a .zndx.engine.v1.CompleteResponse\x12G\n\x06Status\x12\x1d.zndx.engine.v1.StatusRequest\x1a\x1e.zndx.engine.v1.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zndx.engine.v1.engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPLETEREQUEST']._serialized_start=48
  _globals['_COMPLETEREQUEST']._serialized_end=186
  _globals['_COMPLETERESPONSE']._serialized_start=189
  _globals['_COMPLETERESPONSE']._serialized_end=356
  _globals['_STATUSREQUEST']._serialized_start=358
  _globals['_STATUSREQUEST']._serialized_end=373
  _globals['_ENDPOINT']._serialized_start=375
  _globals['_ENDPOINT']._serialized_end=470
  _globals['_STATUSRESPONSE']._serialized_start=472
  _globals['_STATUSRESPONSE']._serialized_end=570
  _globals['_ENGINE']._serialized_start=573
  _globals['_ENGINE']._serialized_end=733
# @@protoc_insertion_point(module_scope)
